# PyTorch tensor walkthrough
- some simple examples of using PyTorch tensor objects

In [1]:
# import required library
import torch

In [2]:
# create a 2-dimensional 5x7 tensor with value 1 in every position
a = torch.ones(5, 7, dtype=torch.float)
a

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [3]:
# define a non-symmetric matrix with zeros and 1's down the diagonal
b = torch.eye(5,7)
b

tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.]])

In [4]:
# define a square identity tensor
c = torch.eye(5,5)
c

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

# Examine tensor elements

In [5]:
b[0]

tensor([1., 0., 0., 0., 0., 0., 0.])

In [6]:
b[0,0]

tensor(1.)

In [7]:
b[2:]

tensor([[0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.]])

# Do operations on the tensors

In [8]:
# add two tensors with identical dimesions
a_plus_b = a + b
a_plus_b

tensor([[2., 1., 1., 1., 1., 1., 1.],
        [1., 2., 1., 1., 1., 1., 1.],
        [1., 1., 2., 1., 1., 1., 1.],
        [1., 1., 1., 2., 1., 1., 1.],
        [1., 1., 1., 1., 2., 1., 1.]])

In [9]:
# multiply two tensors - this cell will produce an error
a_mult_c = a@c
a_mult_c

RuntimeError: mat1 and mat2 shapes cannot be multiplied (5x7 and 5x5)

In [10]:
# define as 7 x 7 identity tensor
d = torch.eye(7,7)
d

tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1.]])

In [11]:
# multiply a tensor by the identity tensor
a_mult_d = a@d
a_mult_d

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [12]:
# transpose a to get a 7x5 matrix
a_trans = torch.transpose(a,0,1)
a_trans

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [13]:
a_trans_mult_c = a_trans @ c
a_trans_mult_c

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])